services:
  db_auth:
    restart: always
    
    container_name: ${POSTGRES_CONTAINER}
    ports:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    image: postgres:${POSTGRES_IMAGE}
